name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - name: yarn install, build
      run: |
        cd functions
        yarn install
    - name: deploy to Firebase Hosting
      run: |
        ./node_modules/.bin/firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
